### ISSUE TITLE
TaskWorker 支持异步操作和协程

### ISSUE THREAD

**Issue by huangzhhui** [swoole/rfc-chinese#27]
目前在 `TaskWorker` 里面使用异步客户端，比如异步Redis，会抛出 `Fatal error: Swoole\Coroutine\Redis::connect(): can't use async-io in task process.`，这样要求了启动阶段执行的代码都要判断是否处于`TaskWorker`，同时也会导致驱动类、业务类的实现会变得复杂，如果 `TaskWorker` 内可以使用异步IO，则很多代码会变得更加的简单。

**Comment by matyhtf** [comment]
已实现，将包含在 4.2.2 版本中发布。
