### ISSUE TITLE
UserWorker中支持使用server->task

### ISSUE THREAD

**Issue by windrunner414** [swoole/rfc-chinese#37]
在UserWorker（例如addProcess的自定义进程）中支持使用task

**Comment by windrunner414** [comment]
在userworker中触发serv->onFinish

**Comment by matyhtf** [comment]
* 用户进程可能没有创建管道，无法从 Task 进程返回数据到用户进程
* 用户进程创加了管道，Task Finish 的结果可能会带来错误的数据
* 多个进程同时执行 task finish可能会发生数据错乱

**Comment by matyhtf** [comment]
增加一个 task 的 flag，表示为单向投递，不允许再返回数据。

**Comment by matyhtf** [comment]
goto https://github.com/swoole/rfc-chinese/issues/38
