### ISSUE TITLE
RFC-1015 : Server->task 允许使用在非 Worker 进程中使用

### ISSUE THREAD

**Issue by matyhtf** [swoole/rfc-chinese#38]
现状
-----
目前在`Master`、`Manager`、`User Process`中无法调用`Server->task`投递任务。
主要原因是非`Worker`进程不方便实现`Server->finish`和`onFinish`回调。

改进
----
增加单向`task`支持，类型为`SW_TASK_NOREPLY`，使`Master`、`Manager`、`User Process`中均可使用`Server->task`投递任务。

**但这个过程只能是单向的**，`onTask`回调中不得使用`Server->finish`或`return`数值，回复任务结果。否则底层会抛出错误信息。

> `taskwait`、`taskCo`、`taskWaitMulti` 依然只允许在`Worker`进程中使用

TaskWorker
-----
在`Task Worker`进程中仍然禁止使用`Server->task`，主要原因是，避免出现永动机，无限递归产生新的任务，导致死锁。

`Task Worker`进程本身定位是消费者进程，其他是生产者，在`Task Worker`中允许投递任务，完全破坏了生产者消费者模型，消费者又是生产者，这产生了混乱。

版本
----
* 预计在`4.2.13`和`4.3.0`版本中添加

**Comment by shiguangqi** [comment]
我觉得只允许在`User Process`中使用`Server->task`投递任务即可。

1. `Master`、`Manager`非工作进程，不该处理任务

2. `Task Worker` 已经是被投递任务的执行体，再投递单向的task任务容易导致task滥用，task严重阻塞。这个功能可以用`Task Woker`中开启协程来代替。

**Comment by matyhtf** [comment]
现在 master manager 进程已经移除了各种限制。过去我们底层设置的约束条件太多了，我们逐渐去掉这个限制，由开发者自己去选择。

**Comment by mineyang** [comment]
UserWorker投递任务，是不是可以设置在worker进程中onFinish？

UserWorker投递 -> Task 执行 -> Worker onFinish

**Comment by matyhtf** [comment]
@mineyang 这个逻辑是有问题的。finish 的意思是结果原路返回。

**Comment by mineyang** [comment]
我现在是做了一个代理，从UserWorker进程里使用sendMessage方法发送worker进程（随机指定），再从worker进程里转发任务，任务完成后返回给worker进程处理

**Comment by matyhtf** [comment]
你这里直接用 sendMessage 就可以实现，不需要中转。
