### ISSUE TITLE
实现exit特性

### ISSUE THREAD

**Issue by sayid** [swoole/rfc-chinese#39]
能不能增加一个特性，方便开发人员实现exit的效果：遇到退出标示后，自动调回到回调函数中，不再执行之后的业务代码，如onRequest,onReceive

这样开发人员就可以利用ob_get_contents,实现exit效果并能把echo的结果输出给客户端

感觉很实用

**Comment by twose** [comment]
https://wiki.swoole.com/wiki/page/977.html
