### ISSUE TITLE
完善文档

### ISSUE THREAD

**Issue by ctfang** [swoole/rfc-chinese#4]
1。完善文档，现在文档基本不更新，已有的文档也是很模糊，描述不清楚。
2。文档的评论，删除无用评论，最好像http://php.net那样，留下的都是使用场景，教程类评论

**Comment by cz1314520** [comment]
文档真的是太简陋了

**Comment by weizengreal** [comment]
+1

**Comment by lhq0826** [comment]
+1

**Comment by zacksleo** [comment]
+1

**Comment by mitoop** [comment]
+1

**Comment by feng409** [comment]
+1

**Comment by carter911** [comment]
+1

**Comment by takashiki** [comment]
+1

**Comment by heyv5** [comment]
+1

**Comment by rootrl** [comment]
+10086

**Comment by yunnian** [comment]
希望大家不要只说文档简陋，能够提供哪个地方不清楚，哪个点没写好可以指出来

**Comment by breath-co2** [comment]
@yunnian 我来说下吧，现在的文档更多的是“API指南”（对我来说足够）但对更多的新手来说恐怕是摸不着头脑的感觉，所以可以考虑整理一个目录更加清晰的“从入门到精通”的文档，更多的是一些最佳实践的使用方法以及一些代码示例，而目前的文档可以整理成为一个更加清晰的API指南更实用。

**Comment by matyhtf** [comment]
请勿评论“+1”等内容。"完善文档" 这种提法太宽泛了，不够具体，没有可执行的方向。

* 文档开发组一直在持续更新维护。另外，目前文档以开放编辑，你们也可以参与文档的贡献
* 建议提出哪些方面不够详细，或者哪个页面的内容不足需要完善，更具体一些

**Comment by carter911** [comment]
希望每个方法函数 有对应的事例,参数对应的说的清楚点

**Comment by twose** [comment]
多看几遍文档以后就会发现说文档不完善的都是人云亦云, 例子也可以到swoole-src的examples里去找.
