### ISSUE TITLE
希望让table支持存对象

### ISSUE THREAD

**Issue by sayid** [swoole/rfc-chinese#46]
我想实现强一致性的分布式事务，需要进程间能共享数据库链接才行，并且能通过id快速的取到连接对象。
可以加上这个特性吗？现在table不能存储对象

**Comment by fdreamsu** [comment]
可以使用Table::TYPE_STRING格式，然后序列化对象存储

**Comment by sayid** [comment]
> 可以使用Table::TYPE_STRING格式，然后序列化对象存储

我希望存储PDO资源链接对象呢

**Comment by twose** [comment]
做不到...

**Comment by sayid** [comment]
> 做不到...

那能单独开一个大空间高可用的内存区域/或者进程吗？用来伺服其他worker进程，通过这个进程或空间做各种资源共享？

**Comment by lizhichao** [comment]
分布式事务 和  进程间能共享数据库链接 有什么关系？
希望每次请求这个服务都是同一个 数据库连接 ？
@sayid
