### ISSUE TITLE
Http\Response 增加 writeHeader 方法，可设置任意 Http Header 输出

### ISSUE THREAD

**Issue by matyhtf** [swoole/rfc-chinese#52]
现状
----
目前底层提供的`Response::header()`方法参数为`Key-Value`方法，并且存在一个一维数组中。**因此不支持重复的 Http Header 设置**。

根据`Http`协议，`Http Header`是可以重复的。因此需要增加一个`Http\Response::writeHeader`设置任意`Http Header`。

代码
----
方法接受一个字符串参数，末尾不需要加`\r\n`，需要进行`rtrim`操作，避免用户代码添加额外的`CRLF`导致协议错误。

应用层应当自行对字符进行 URL 编码，底层仅拼接字符串并输出。

```php
$http = new Swoole\Http\Server("127.0.0.1", 9501);
$http->on('request', function ($request, $response) {
    $response->writeHeader("X-Info: PHP");
    $response->writeHeader("X-Info: Swoole");
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});
$http->start();
```

对端浏览器将收到一个重复的`X-Info`头。

```
HTTP/2.0 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Sun, 21 Apr 2019 13:43:16 GMT
X-Info: PHP
X-Info: Swoole
```

实现
----
* `Http\Response`底层增加一个`rawHeaders`属性
* `Http\Response::writeHeader`操作向该属性数组中追加字符串元素
* 构建`Response`数据包时，在`headers`之后追加`rawHeaders`内容

**Comment by hhxsv5** [comment]
个人觉得这属于Bug修复，建议底层存储结构改为`二维数组`，然后`Response::header() `函数第二参数`$value`同时支持`字符串`和`数组`，发版本时说明下这个变更。

**Comment by matyhtf** [comment]
@hhxsv5 非常好的提议。赞

**Comment by matyhtf** [comment]
goto https://github.com/swoole/rfc-chinese/issues/53
