### ISSUE TITLE
RFC-1021: Http\Response::header 第二个参数支持数组，可设置多个相同的 Header

### ISSUE THREAD

**Issue by matyhtf** [swoole/rfc-chinese#53]
现状
----
目前底层提供的`Response::header()`方法第二个参数为`String`类型，**不支持设置多个的 Http Header**。

根据`Http`协议，`Http Header`是可以重复的。因此需要修改`Http\Response::header`方法，可以设置多个`Http Header`。

代码
----
```php
$http = new Swoole\Http\Server("127.0.0.1", 9501);
$http->on('request', function ($request, $response) {
    $response->header("X-Info", ["PHP", "Swoole"]);
    $response->header("X-Power-By", "Swoole");
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});
$http->start();
```

对端浏览器将收到一个重复的`X-Info`头。

```
HTTP/2.0 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Sun, 21 Apr 2019 13:43:16 GMT
X-Info: PHP
X-Info: Swoole
```

实现
----
* `Http\Response::header`支持设置数组
* 构建`Response`数据包时，检查`Key`对应的`Value`是字符串还是数组
* 如果是数组，底层会循环输出多次

**Comment by Moln** [comment]
感觉不那么重要，都是通过自己多次设置 header 解决.
